// Each service has its own content and equivalent French, English and Spanish URLs.
export const locales = {
  fr: {
    lang: 'fr-CA', home: '/', about: 'a-propos.html', contact: 'contact.html',
    homeFile: 'demo-finance.html', homeLabel: 'Accueil', services: 'Services',
    includes: 'Ce que je peux prendre en charge', example: 'Un exemple concret',
    prepare: 'Pour commencer', faq: 'Vos questions', related: 'Services complémentaires',
    cta: 'Parlons de vos besoins', ctaText: 'Vous souhaitez déléguer cette tâche ? Contactez Aurélie Genin pour préciser votre besoin, les documents disponibles et le rythme de travail souhaité.',
    local: 'Basée à Saint-Élie-de-Caxton, GESCOM accompagne à distance les entrepreneurs, travailleurs autonomes et PME de Mauricie, notamment à Trois-Rivières et Shawinigan.',
    processTitle: 'Comment se déroule la collaboration ?',
    process: ['Nous définissons ensemble les tâches à déléguer, vos priorités et les échéances.', 'Vous partagez les documents et les accès nécessaires selon les modalités convenues.', 'Je prends en charge les tâches retenues et vous transmets un suivi des points à valider.'],
    more: 'Découvrir ce service',
  },
  en: {
    lang: 'en-CA', home: '/demo-finance-en.html', about: 'about-en.html', contact: 'contact-en.html',
    homeFile: 'demo-finance-en.html', homeLabel: 'Home', services: 'Services',
    includes: 'What I can take care of', example: 'A practical example',
    prepare: 'Getting started', faq: 'Your questions', related: 'Related services',
    cta: 'Let’s discuss your needs', ctaText: 'Ready to delegate this task? Contact Aurélie Genin to discuss your needs, the documents available and your preferred working schedule.',
    local: 'Based in Saint-Élie-de-Caxton, GESCOM provides remote support to entrepreneurs, self-employed professionals and small businesses in Mauricie, including Trois-Rivières and Shawinigan.',
    processTitle: 'How will we work together?',
    process: ['Together, we define the tasks you want to delegate, your priorities and deadlines.', 'You share the necessary documents and access using the arrangements we agree on.', 'I handle the agreed tasks and keep you informed of any points requiring your approval.'],
    more: 'Explore this service',
  },
  es: {
    lang: 'es', home: '/demo-finance-es.html', about: 'acerca-de.html', contact: 'contacto.html',
    homeFile: 'demo-finance-es.html', homeLabel: 'Inicio', services: 'Servicios',
    includes: 'De qué puedo encargarme', example: 'Un ejemplo práctico',
    prepare: 'Para empezar', faq: 'Sus preguntas', related: 'Servicios complementarios',
    cta: 'Hablemos de sus necesidades', ctaText: '¿Quiere delegar esta tarea? Contacte con Aurélie Genin para concretar sus necesidades, los documentos disponibles y el ritmo de trabajo deseado.',
    local: 'Desde Saint-Élie-de-Caxton, GESCOM acompaña a distancia a emprendedores, trabajadores autónomos y pymes de Mauricie, especialmente en Trois-Rivières y Shawinigan.',
    processTitle: '¿Cómo se desarrolla la colaboración?',
    process: ['Definimos juntos las tareas que desea delegar, sus prioridades y los plazos.', 'Comparte los documentos y accesos necesarios según las modalidades acordadas.', 'Me encargo de las tareas acordadas y le informo de los puntos pendientes de su validación.'],
    more: 'Conocer este servicio',
  },
};

export const services = [
  {
    fr: {
      slug: 'gestion-administrative-mauricie', title: 'Gestion administrative en Mauricie',
      description: 'Déléguez vos tâches administratives à GESCOM en Mauricie : documents, courriels, classement et suivi des dossiers pour entrepreneurs et PME.',
      intro: 'Les courriels, les documents à préparer et les dossiers à suivre prennent du temps sur votre activité. Je vous accompagne à distance pour organiser cet administratif et prendre en charge les tâches que vous souhaitez déléguer, de façon ponctuelle ou régulière.',
      tasks: ['Saisie et mise à jour de vos données, préparation de documents et suivi des échéances.', 'Tri des courriels professionnels, préparation de réponses et suivi des demandes prioritaires.', 'Classement numérique, numérisation et organisation des contrats et documents de travail.', 'Mise à jour des fichiers clients et du CRM, coordination des rendez-vous et relances commerciales.'],
      example: 'Vous retrouvez des demandes clients dans plusieurs courriels et ne savez plus lesquelles attendent une réponse. Nous définissons un classement et un tableau de suivi. Je regroupe les informations, prépare les réponses prévues et vous signale les décisions à prendre.',
      prepare: 'Identifiez les tâches qui vous prennent le plus de temps, les outils que vous utilisez et vos prochaines échéances. Nous convenons ensuite des accès utiles, des consignes de traitement et des validations qui restent entre vos mains.',
      questions: [['Puis-je demander une aide ponctuelle ?', 'Oui. Le soutien peut répondre à une période chargée, à un besoin de classement ou à un suivi régulier. Le périmètre et le rythme sont définis ensemble.'], ['Faut-il changer mes outils ?', 'La collaboration part de vos outils et de vos procédures. Nous précisons ensemble les accès et les adaptations nécessaires avant la prise en charge.']],
    },
    en: {
      slug: 'administrative-support-mauricie', title: 'Administrative support in Mauricie',
      description: 'Remote administrative support from GESCOM in Mauricie: documents, email management, filing and client follow-up for entrepreneurs and small businesses.',
      intro: 'Emails, documents and unfinished administrative tasks take time away from running your business. I provide remote support to organize this work and handle the tasks you choose to delegate, whether you need occasional help or regular assistance.',
      tasks: ['Data entry and updates, document preparation and deadline tracking.', 'Professional email sorting, draft replies and follow-up on priority requests.', 'Digital filing, document scanning and organization of contracts and working documents.', 'Client and CRM updates, appointment coordination and sales follow-up.'],
      example: 'Customer requests are spread across several emails and it is unclear which ones still need a reply. Together, we define a filing system and tracking sheet. I bring the information together, prepare agreed replies and flag decisions for you.',
      prepare: 'Identify the tasks taking up most of your time, the tools you use and upcoming deadlines. We then agree on the access needed, processing instructions and approvals that remain with you.',
      questions: [['Can I request occasional help?', 'Yes. Support can cover a busy period, a filing project or regular follow-up. We agree on the scope and schedule together.'], ['Do I need to change my tools?', 'We start with your existing tools and procedures, then clarify the access and any adjustments needed before work begins.']],
    },
    es: {
      slug: 'gestion-administrativa-mauricie', title: 'Gestión administrativa en Mauricie',
      description: 'Apoyo administrativo a distancia con GESCOM en Mauricie: documentos, correos, archivo y seguimiento de expedientes para emprendedores y pymes.',
      intro: 'Los correos, los documentos por preparar y los expedientes pendientes restan tiempo a su actividad. Le acompaño a distancia para organizar ese trabajo y encargarme de las tareas que desea delegar, de forma puntual o periódica.',
      tasks: ['Registro y actualización de datos, preparación de documentos y seguimiento de plazos.', 'Clasificación de correos profesionales, preparación de respuestas y seguimiento de solicitudes prioritarias.', 'Archivo digital, digitalización y organización de contratos y documentos de trabajo.', 'Actualización de archivos de clientes y del CRM, coordinación de citas y seguimiento comercial.'],
      example: 'Las solicitudes de sus clientes están repartidas entre varios correos y no sabe cuáles esperan respuesta. Definimos un sistema de archivo y una tabla de seguimiento. Reúno la información, preparo las respuestas acordadas y le señalo las decisiones pendientes.',
      prepare: 'Identifique las tareas que más tiempo le quitan, las herramientas que utiliza y sus próximos plazos. Acordamos los accesos necesarios, las instrucciones y las validaciones que quedan en sus manos.',
      questions: [['¿Puedo solicitar ayuda puntual?', 'Sí. El apoyo puede cubrir una temporada de mucho trabajo, una necesidad de archivo o un seguimiento periódico. Definimos juntos el alcance y el ritmo.'], ['¿Tengo que cambiar mis herramientas?', 'Partimos de sus herramientas y procedimientos. Aclaramos los accesos y las adaptaciones necesarias antes de comenzar.']],
    },
  },
  {
    fr: {
      slug: 'devis-facturation-mauricie', title: 'Devis et facturation en Mauricie',
      description: 'GESCOM prépare vos devis et factures et assure le suivi des paiements en Mauricie. Un soutien à distance pour une facturation organisée et régulière.',
      intro: 'Entre les prestations réalisées, les devis à envoyer et les paiements à suivre, la facturation peut vite prendre du retard. Je vous aide à garder un suivi clair de vos documents commerciaux et des prochaines actions à effectuer.',
      tasks: ['Préparation des devis à partir de vos tarifs et des informations que vous fournissez.', 'Création et envoi des factures selon les éléments validés avec vous.', 'Mise à jour du suivi des paiements et repérage des factures en attente.', 'Préparation des relances clients et classement des documents de facturation.'],
      example: 'Vous avez terminé plusieurs prestations, mais les informations utiles à la facturation sont dispersées. Je rassemble les éléments, prépare les factures pour validation et mets à jour un suivi indiquant les documents envoyés, les paiements reçus et les relances à prévoir.',
      prepare: 'Préparez vos coordonnées de facturation, vos modèles de devis, vos tarifs, les informations clients et l’état des factures en cours. Nous définissons qui valide les documents et à quel moment les envoyer ou relancer.',
      questions: [['Qui décide des tarifs et des conditions ?', 'Vous conservez la décision sur vos prix, vos conditions et vos engagements commerciaux. Les documents sont préparés selon vos consignes.'], ['Le service comprend-il le suivi des factures existantes ?', 'Oui. Nous pouvons partir de vos factures déjà émises pour organiser le suivi des paiements et les relances convenues.']],
    },
    en: {
      slug: 'quotes-invoicing-mauricie', title: 'Quotes and invoicing in Mauricie',
      description: 'GESCOM prepares quotes and invoices and tracks payments in Mauricie. Remote support to keep your invoicing organized and consistent.',
      intro: 'Completed work, quotes waiting to be sent and payments to track can quickly create an invoicing backlog. I help you keep a clear record of your sales documents and the next actions required.',
      tasks: ['Quote preparation using your rates and the information you provide.', 'Invoice creation and sending based on the details approved with you.', 'Payment tracking updates and identification of outstanding invoices.', 'Client reminder preparation and organization of invoicing records.'],
      example: 'You have completed several jobs, but the billing information is scattered. I gather the details, prepare invoices for approval and update a tracking sheet showing documents sent, payments received and reminders to schedule.',
      prepare: 'Gather your billing details, quote templates, rates, client information and current invoices. We define who approves each document and when invoices or reminders should be sent.',
      questions: [['Who decides on pricing and terms?', 'You retain control over prices, terms and commercial commitments. Documents are prepared according to your instructions.'], ['Can you track invoices already issued?', 'Yes. We can start with existing invoices to organize payment tracking and the reminders agreed with you.']],
    },
    es: {
      slug: 'presupuestos-facturacion-mauricie', title: 'Presupuestos y facturación en Mauricie',
      description: 'GESCOM prepara presupuestos y facturas y realiza el seguimiento de pagos en Mauricie. Apoyo a distancia para una facturación organizada.',
      intro: 'Entre los trabajos terminados, los presupuestos por enviar y los pagos pendientes, la facturación puede acumular retrasos. Le ayudo a mantener un registro claro de sus documentos comerciales y de las próximas acciones.',
      tasks: ['Preparación de presupuestos a partir de sus tarifas y de la información que facilita.', 'Creación y envío de facturas según los elementos validados con usted.', 'Actualización del seguimiento de pagos e identificación de facturas pendientes.', 'Preparación de recordatorios a clientes y archivo de documentos de facturación.'],
      example: 'Ha terminado varios trabajos, pero los datos de facturación están dispersos. Reúno la información, preparo las facturas para su validación y actualizo un registro con los documentos enviados, los pagos recibidos y los recordatorios previstos.',
      prepare: 'Reúna sus datos de facturación, modelos de presupuesto, tarifas, información de clientes y facturas en curso. Definimos quién valida los documentos y cuándo enviarlos o recordar un pago.',
      questions: [['¿Quién decide las tarifas y condiciones?', 'Usted conserva la decisión sobre precios, condiciones y compromisos comerciales. Los documentos se preparan siguiendo sus instrucciones.'], ['¿Se incluyen las facturas ya emitidas?', 'Sí. Podemos partir de sus facturas existentes para organizar el seguimiento de pagos y los recordatorios acordados.']],
    },
  },
  {
    fr: {
      slug: 'tenue-de-livres-mauricie', title: 'Tenue de livres en Mauricie',
      description: 'Tenue de livres à distance en Mauricie avec GESCOM : revenus, dépenses, pièces justificatives et rapprochements bancaires pour entrepreneurs et PME.',
      intro: 'Des reçus éparpillés et des transactions en attente compliquent le suivi de votre entreprise. Je vous aide à tenir des dossiers comptables organisés en saisissant les opérations et en rapprochant les documents disponibles.',
      tasks: ['Saisie et catégorisation des revenus et des dépenses à partir des pièces fournies.', 'Classement des factures, reçus et autres pièces justificatives.', 'Rapprochements bancaires et repérage des écarts à clarifier.', 'Préparation de dossiers structurés à transmettre à votre comptable.'],
      example: 'À la fin du mois, vos relevés bancaires et vos reçus ne sont pas regroupés. Je classe les pièces, saisis les transactions et rapproche les mouvements. Les documents manquants ou les opérations à préciser sont réunis dans une liste pour votre suivi.',
      prepare: 'Rassemblez vos relevés, factures de vente, factures fournisseurs et reçus pour la période concernée. Indiquez l’outil comptable utilisé et les consignes de votre comptable afin de garder une organisation cohérente.',
      questions: [['Quels documents dois-je fournir ?', 'Les relevés de la période, les factures de vente et d’achat et les justificatifs de dépenses constituent le point de départ. Nous précisons les éléments manquants selon vos dossiers.'], ['Comment faire le lien avec mon comptable ?', 'Le classement et les dossiers peuvent être organisés selon ses consignes. Les points qui demandent une décision ou une validation lui sont transmis par votre intermédiaire ou selon les modalités convenues.']],
    },
    en: {
      slug: 'bookkeeping-mauricie', title: 'Bookkeeping in Mauricie',
      description: 'Remote bookkeeping in Mauricie with GESCOM: income, expenses, supporting documents and bank reconciliations for entrepreneurs and small businesses.',
      intro: 'Scattered receipts and transactions waiting to be entered make business records harder to follow. I help keep your bookkeeping organized by recording transactions and matching the documents available.',
      tasks: ['Income and expense entry and categorization using the documents provided.', 'Organization of invoices, receipts and other supporting records.', 'Bank reconciliations and identification of differences to clarify.', 'Preparation of organized records to share with your accountant.'],
      example: 'At the end of the month, bank statements and receipts have not been brought together. I organize the documents, record transactions and reconcile movements. Missing records and transactions needing clarification are listed for your follow-up.',
      prepare: 'Gather bank statements, sales invoices, supplier invoices and receipts for the relevant period. Let me know which bookkeeping tool you use and your accountant’s instructions so the records remain consistent.',
      questions: [['Which documents should I provide?', 'Statements for the period, sales and purchase invoices and expense receipts are the starting point. We identify anything missing as we review your records.'], ['How does this connect with my accountant?', 'Files can be organized according to your accountant’s instructions. Points requiring a decision or approval are shared through you or using the arrangements agreed together.']],
    },
    es: {
      slug: 'teneduria-de-libros-mauricie', title: 'Teneduría de libros en Mauricie',
      description: 'Teneduría de libros a distancia en Mauricie con GESCOM: ingresos, gastos, justificantes y conciliaciones bancarias para emprendedores y pymes.',
      intro: 'Los recibos dispersos y las operaciones pendientes dificultan el seguimiento de su empresa. Le ayudo a mantener sus registros contables organizados mediante el registro de operaciones y la conciliación de los documentos disponibles.',
      tasks: ['Registro y clasificación de ingresos y gastos a partir de los justificantes facilitados.', 'Archivo de facturas, recibos y otros documentos de respaldo.', 'Conciliaciones bancarias e identificación de diferencias por aclarar.', 'Preparación de expedientes organizados para entregar a su contable.'],
      example: 'Al terminar el mes, los extractos bancarios y los recibos siguen separados. Archivo los documentos, registro las operaciones y concilio los movimientos. Los justificantes que faltan y las operaciones por aclarar se reúnen en una lista para su seguimiento.',
      prepare: 'Reúna los extractos, las facturas de venta, las facturas de proveedores y los recibos del período. Indique la herramienta contable y las instrucciones de su contable para mantener una organización coherente.',
      questions: [['¿Qué documentos debo facilitar?', 'Los extractos del período, las facturas de venta y compra y los justificantes de gastos son el punto de partida. Precisamos los elementos que faltan al revisar los expedientes.'], ['¿Cómo se coordina con mi contable?', 'El archivo puede organizarse según sus instrucciones. Los puntos que requieren una decisión o validación se transmiten a través de usted o según las modalidades acordadas.']],
    },
  },
  {
    fr: {
      slug: 'rapports-taxes-tps-tvq-mauricie', title: 'Préparation des rapports TPS/TVQ en Mauricie',
      description: 'GESCOM vous aide à préparer vos rapports de taxes TPS/TVQ en Mauricie : compilation des données, pièces justificatives et suivi des périodes.',
      intro: 'La préparation de vos rapports de taxes commence par des données comptables organisées. Je rassemble les informations utiles, compile les montants et vous aide à suivre les périodes à traiter pour que votre dossier soit prêt à être validé.',
      tasks: ['Regroupement des documents de vente et d’achat pour la période concernée.', 'Compilation des montants de TPS et de TVQ à partir de vos données comptables.', 'Vérification de la cohérence des montants et repérage des pièces manquantes.', 'Préparation d’un récapitulatif et suivi des échéances que vous communiquez.'],
      example: 'Une période de déclaration approche et certaines factures ne sont pas encore classées. Je rassemble les pièces de cette période, compile les taxes figurant dans les dossiers et liste les éléments à vérifier avant votre validation du rapport.',
      prepare: 'Prévoyez les dates de la période, les documents comptables correspondants, vos informations d’inscription et les consignes de votre comptable. Nous précisons ensemble les étapes de préparation et la personne responsable de la validation et de la transmission.',
      questions: [['La tenue de livres doit-elle être à jour ?', 'Des dossiers à jour facilitent la préparation. Si des transactions ou des justificatifs manquent, nous identifions d’abord les éléments à compléter.'], ['Qui valide et transmet le rapport ?', 'Les responsabilités de validation et de transmission sont définies avec vous avant la mission. Les questions de traitement fiscal à clarifier sont soumises à votre comptable.']],
    },
    en: {
      slug: 'gst-qst-reports-mauricie', title: 'GST/QST report preparation in Mauricie',
      description: 'GESCOM helps prepare GST/QST reports in Mauricie: data compilation, supporting documents and reporting-period tracking for your business.',
      intro: 'Preparing tax reports starts with organized bookkeeping records. I bring together the information needed, compile amounts and help track the periods to process so your file is ready for review.',
      tasks: ['Collection of sales and purchase documents for the relevant period.', 'Compilation of GST and QST amounts from your bookkeeping records.', 'Consistency checks and identification of missing supporting documents.', 'Preparation of a summary and tracking of the deadlines you provide.'],
      example: 'A reporting period is approaching and some invoices have not been filed. I collect the documents for that period, compile the taxes recorded in your files and list the points to check before you approve the report.',
      prepare: 'Have the period dates, corresponding bookkeeping records, registration information and your accountant’s instructions ready. Together, we clarify the preparation steps and who is responsible for approval and submission.',
      questions: [['Does my bookkeeping need to be up to date?', 'Current records make preparation easier. If transactions or supporting documents are missing, we first identify what needs to be completed.'], ['Who approves and submits the report?', 'Approval and submission responsibilities are agreed with you before the assignment. Questions about tax treatment are referred to your accountant.']],
    },
    es: {
      slug: 'informes-tps-tvq-mauricie', title: 'Preparación de informes TPS/TVQ en Mauricie',
      description: 'GESCOM le ayuda a preparar informes TPS/TVQ en Mauricie: recopilación de datos, justificantes y seguimiento de los períodos de declaración.',
      intro: 'La preparación de los informes de impuestos comienza con datos contables organizados. Reúno la información necesaria, compilo los importes y le ayudo a seguir los períodos pendientes para que el expediente esté listo para su revisión.',
      tasks: ['Recopilación de documentos de venta y compra del período correspondiente.', 'Compilación de importes de TPS y TVQ a partir de sus datos contables.', 'Verificación de coherencia e identificación de justificantes que faltan.', 'Preparación de un resumen y seguimiento de los plazos que comunica.'],
      example: 'Se acerca un período de declaración y algunas facturas todavía no están archivadas. Reúno los documentos del período, compilo los impuestos registrados y enumero los puntos que revisar antes de que valide el informe.',
      prepare: 'Prepare las fechas del período, los documentos contables correspondientes, sus datos de inscripción y las instrucciones de su contable. Precisamos las etapas y quién se encarga de validar y transmitir el informe.',
      questions: [['¿Los libros deben estar al día?', 'Los registros actualizados facilitan la preparación. Si faltan operaciones o justificantes, identificamos primero lo que hay que completar.'], ['¿Quién valida y transmite el informe?', 'Las responsabilidades se acuerdan con usted antes de comenzar. Las cuestiones de tratamiento fiscal por aclarar se remiten a su contable.']],
    },
  },
];
